spring.application.name=astromock
spring.datasource.url=jdbc:postgresql://localhost:5432/astro
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

spring.security.user.name=admin
spring.security.user.password=admin123


jwt.secret=${JWT_SECRET}


#jvdsajgsjh3hv4q3bmhv3wmve3h43mhvqmvmavmasvcmsvcmsdvcmsdvcmsdvcmsdvcmsdcmsdvcmsdcmdsbcmdsvcmsdvcmsdvmcsdvcvsdvsn





